apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{.Chart.Name}}-{{.Chart.Version}}
  name: {{.Chart.Name}}

  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.nginx_image.repository }}:{{ .Values.nginx_image.tag }}
    name: nginx
    resources:
      requests:
         cpu: {{ .Values.resources.limits.cpu }} 
         memory: {{ .Values.resources.limits.memory }}
